server:
  port: 80
spring:
  application:
    name: springcloud-consumer-dept
eureka:
  client:
    # 消费者只需要去获取注册列表即可，不需要注册
#    register-with-eureka: false
    # 如果使用 Zuul（Gateway），就必须注册，让 Zuul 能通过 Eureka 找到 Consumer
    register-with-eureka: true
    # 填写所有提供注册中心服务的地址，Ribbon 会根据负载均衡算法自动分配要访问的地址
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
# 如果 Consumer 使用了 hystrix，一定要加上这个配置，不过主启动类不需要加 @EnableCircuitBreaker
# 如果是 Provider 的话就不用写这个配置，但是主启动类一定要加 @EnableCircuitBreaker
feign:
  hystrix:
    enabled: true

